version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      network: host
    ports:
      - 8083:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV:production
  backend:
    build:
      context: ./backend
      network: host
    ports:
      - "8082:80"
    environment:
      - UVICORN_WORKERS-2
      - DECISION_ENGINE_URL=http://decision-engine:80
      - MYOB_URL=http://accounting-software:80/xero/balances
      - XERO_URL=http://accounting-software:80/myob/balances
    command: uvicorn main:app --host 0.0.0.0 --port 80
    links:
      - "accounting-software"
      - "decision-engine"
  accounting-software:
    build:
      context: ./external/accounting-software
      network: host
    ports:
      - "8081:80"
    environment:
      - UVICORN_WORKERS=2  # Optional, to set the number of Uvicorn workers
    command: uvicorn main:app --host 0.0.0.0 --port 80  # Assuming 'main.py' and FastAPI app instance named 'app'
  decision-engine:
    build:
      context: ./external/decision-engine
      network: host
    ports:
      - "8080:80"
    environment:
      - UVICORN_WORKERS=2  # Optional, to set the number of Uvicorn workers
    command: uvicorn main:app --host 0.0.0.0 --port 80  # Assuming 'main.py' and FastAPI app instance named 'app'
