version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8083:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV:production
  backend:
    build:
      context: ./backend
    ports:
      - "8082:80"
    environment:
      - UVICORN_WORKERS-2
    command: uvicorn main:app --host 0.0.0.0 --port 80
  accounting-software:
    build:
      context: ./external/accounting-software
    ports:
      - "8081:80"
    environment:
      - UVICORN_WORKERS=2  # Optional, to set the number of Uvicorn workers
    command: uvicorn main:app --host 0.0.0.0 --port 80  # Assuming 'main.py' and FastAPI app instance named 'app'
  decision-engine:
    build:
      context: ./external/decision-engine
    ports:
      - "8080:80"
    environment:
      - UVICORN_WORKERS=2  # Optional, to set the number of Uvicorn workers
    command: uvicorn main:app --host 0.0.0.0 --port 80  # Assuming 'main.py' and FastAPI app instance named 'app'
